version: '2.1'

services:
  devimage:
    image: "winjitamol/nodedockertest"
    build: .
    environment:
      NODE_ENV: "development"
      PORT: "8080"
    ports:
      - "8080:8080" 
    container_name: "dev_container"
    
  prodimage:
    image: "winjitamol/nodedockerprod"
    build: .
    depends_on:
      redis:
        condition: service_started
    environment:
      NODE_ENV: "production"
      PORT: "8081"
    ports:
      - "8081:8081"
    container_name: "prod_container"

  redis:
    image: redis